### PR TITLE
Install packages required by pip to build python packages

### PR DESCRIPTION
**Pull request by fdhmcts**

### CODE REVIEW

**Review by kyrian-hmcts — CHANGES_REQUESTED** [review]
The fix to github.com is fine, but adding yet another list of packages to be installed doesn't make so much sense. Why not just leverage the existing packages list? Also, having a compiler on live systems isn't necessarily a good idea.

**Comment by fdhmcts** [comment]
How do you make "pip install" work without installing gcc ? I wish pip is able to fetch binaries for all packages but unfortunately it seems to have to build some of them (required for azure-2.0.0)

**Comment by fdhmcts** [comment]
Simplest alternative is https://github.com/hmcts/ansible-management/pull/261

**Comment by fdhmcts** [comment]
https://github.com/hmcts/ansible-management/pull/261 has been merged so we should not need this change any more

**Pull request closed without merging**
